services:
  web:
    build: .
    container_name: thesis-container
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload
    ports: 
      - "8000:8000"
    volumes: 
      - .:/app
    # env_file:
      # - server/.env
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: postgres_db_thesis
    environment:
      - POSTGRES_DB=thesis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
